### ISSUE TITLE
indexing error with original urbs example case

### ISSUE THREAD

**Issue by dacoex** [tum-ens/urbs#11]
```
python runme.py
GLPSOL: GLPK LP/MIP Solver, v4.52
Parameter(s) specified in the command line:
 --log result/mimo-example-20150622T222334/scenario_base-20150622T222336.log
 --write /tmp/tmp156QX6.glpk.raw --wglp /tmp/tmpxX71e8.glpk.glp --cpxlp /tmp/tmp2sxhvX.pyomo.lp
Reading problem data from '/tmp/tmp2sxhvX.pyomo.lp'...
33249 rows, 28889 columns, 88590 non-zeros
217237 lines were read
Writing problem data to `/tmp/tmpxX71e8.glpk.glp'...
165932 lines were written
GLPK Simplex Optimizer, v4.52
33249 rows, 28889 columns, 88590 non-zeros
Preprocessing...
21929 rows, 18809 columns, 57072 non-zeros
Scaling...
 A: min|aij| =  2.463e-04  max|aij| =  3.635e+01  ratio =  1.476e+05
GM: min|aij| =  2.477e-01  max|aij| =  4.038e+00  ratio =  1.630e+01
EQ: min|aij| =  6.134e-02  max|aij| =  1.000e+00  ratio =  1.630e+01
Constructing initial basis...
Size of triangular part is 21926
      0: obj =   2.949480711e+09  infeas =  9.701e+06 (3)
    500: obj =   8.173133100e+10  infeas =  4.043e+06 (3)
*   683: obj =   3.139296267e+11  infeas =  0.000e+00 (3)
*  1000: obj =   2.775929953e+11  infeas =  1.442e-10 (3)
*  1500: obj =   1.291434308e+11  infeas =  1.820e-11 (3)
*  2000: obj =   4.522765150e+10  infeas =  3.741e-13 (3)
*  2500: obj =   3.872770655e+10  infeas =  2.839e-14 (3)
*  3000: obj =   3.598858410e+10  infeas =  1.021e-13 (3)
*  3500: obj =   3.485474403e+10  infeas =  2.220e-16 (3)
*  4000: obj =   3.388197654e+10  infeas =  0.000e+00 (3)
*  4500: obj =   3.303325605e+10  infeas =  1.616e-12 (3)
*  5000: obj =   3.237474655e+10  infeas =  1.058e-14 (3)
*  5500: obj =   3.177669129e+10  infeas =  2.572e-12 (3)
*  6000: obj =   3.122633187e+10  infeas =  3.597e-12 (3)
*  6500: obj =   3.091102827e+10  infeas =  0.000e+00 (3)
*  7000: obj =   3.049157027e+10  infeas =  1.257e-13 (3)
*  7500: obj =   3.026133732e+10  infeas =  1.462e-10 (3)
*  8000: obj =   2.980215464e+10  infeas =  3.051e-12 (3)
*  8500: obj =   2.917891805e+10  infeas =  1.771e-12 (3)
*  9000: obj =   2.899585804e+10  infeas =  0.000e+00 (3)
*  9500: obj =   2.876866471e+10  infeas =  0.000e+00 (3)
*  9647: obj =   2.876766525e+10  infeas =  0.000e+00 (3)
OPTIMAL LP SOLUTION FOUND
Time used:   13.3 secs
Memory used: 34.4 Mb (36105158 bytes)
Writing basic solution to `/tmp/tmp156QX6.glpk.raw'...
62140 lines were written
Traceback (most recent call last):
  File "runme.py", line 163, in <module>
    result_dir, plot_periods=periods)
  File "runme.py", line 124, in run_scenario
    periods=plot_periods)
  File "/home/hotryce/urbs/urbs.py", line 1541, in result_figures
    fig = plot(prob, com, sit, timesteps=timesteps)
  File "/home/hotryce/urbs/urbs.py", line 1484, in plot
    ax1.set_ylim((0, csto.loc[sit, :, com]['C Total'].sum()))
  File "/usr/lib/python2.7/dist-packages/pandas/core/indexing.py", line 1026, in __getitem__
    return self._getitem_tuple(key)
  File "/usr/lib/python2.7/dist-packages/pandas/core/indexing.py", line 602, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/usr/lib/python2.7/dist-packages/pandas/core/indexing.py", line 107, in _has_valid_tuple
    raise IndexingError('Too many indexers')
pandas.core.indexing.IndexingError: Too many indexers

```

**Comment by ojdo** [comment]
Thank you for reporting! However, I cannot reproduce that behaviour on my systems. I fear it has to do with using the new version pandas 4.0 (like in #12) , which I currently have no time to add support to. I added issue #13. If you get this error with `coopr.pyomo` (i.e. version < 4), I'll reopen.
