### ISSUE TITLE
RuntimeError: Invalid DISPLAY variable

### ISSUE THREAD

**Issue by louischaman** [tum-ens/urbs#160]
I get this error when running 

python runme.py

```
(urbs) ubuntu@ip-10-125-10-9:~/urbs$ python runme.py
/home/ubuntu/urbs/urbs/input.py:72: FutureWarning: sortlevel is deprecated, use sort_index(level= ...)
  data[key].sortlevel(inplace=True)
GLPSOL: GLPK LP/MIP Solver, v4.63
Parameter(s) specified in the command line:
 --log result/mimo-example-20171025T1004/scenario_base.log --write /tmp/tmp3tgqjm7d.glpk.raw
 --wglp /tmp/tmpmfm67jna.glpk.glp --cpxlp /tmp/tmpzhne28ri.pyomo.lp
Reading problem data from '/tmp/tmpzhne28ri.pyomo.lp'...
33917 rows, 34372 columns, 120746 non-zeros
256884 lines were read
Writing problem data to '/tmp/tmpmfm67jna.glpk.glp'...
204933 lines were written
GLPK Simplex Optimizer, v4.63
33917 rows, 34372 columns, 120746 non-zeros
Preprocessing...
23403 rows, 24886 columns, 89828 non-zeros
Scaling...
 A: min|aij| =  2.463e-04  max|aij| =  5.214e+01  ratio =  2.117e+05
GM: min|aij| =  2.477e-01  max|aij| =  4.038e+00  ratio =  1.630e+01
EQ: min|aij| =  6.134e-02  max|aij| =  1.000e+00  ratio =  1.630e+01
Constructing initial basis...
Size of triangular part is 23400
      0: obj =   5.512063459e+11 inf =   9.464e+05 (80)
    167: obj =   6.217230412e+11 inf =   1.876e-12 (0) 1
*  4459: obj =   7.916941596e+10 inf =   1.499e-11 (4755) 29
*  7744: obj =   4.933462694e+10 inf =   5.844e-11 (5416) 24
* 10748: obj =   4.222957278e+10 inf =   1.588e-11 (5376) 22
* 13536: obj =   3.554103122e+10 inf =   1.343e-10 (6003) 21
* 16293: obj =   3.271075544e+10 inf =   3.903e-10 (4100) 21
* 19086: obj =   3.011547610e+10 inf =   4.862e-10 (6162) 21
* 22172: obj =   2.886713746e+10 inf =   1.435e-10 (2691) 21
* 23855: obj =   2.850869832e+10 inf =   6.966e-11 (0) 12
OPTIMAL LP SOLUTION FOUND
Time used:   37.7 secs
Memory used: 42.1 Mb (44141847 bytes)
Writing basic solution to '/tmp/tmp3tgqjm7d.glpk.raw'...
68298 lines were written
/home/ubuntu/urbs/urbs/output.py:44: FutureWarning: sortlevel is deprecated, use sort_index(level= ...)
  cpro.sortlevel(inplace=True)
/home/ubuntu/urbs/urbs/output.py:48: FutureWarning: sortlevel is deprecated, use sort_index(level= ...)
  ctra.sortlevel(inplace=True)
/home/ubuntu/urbs/urbs/output.py:51: FutureWarning: sortlevel is deprecated, use sort_index(level= ...)
  csto.sortlevel(inplace=True)
Traceback (most recent call last):
  File "runme.py", line 199, in <module>
    report_tuples=report_tuples)
  File "runme.py", line 143, in run_scenario
    figure_size=(24, 9))
  File "/home/ubuntu/urbs/urbs/plot.py", line 333, in result_figures
    fig = plot(prob, com, sit, timesteps=timesteps, **kwds)
  File "/home/ubuntu/urbs/urbs/plot.py", line 145, in plot
    fig = plt.figure(figsize=figure_size)
  File "/home/ubuntu/miniconda3/envs/urbs/lib/python3.6/site-packages/matplotlib/pyplot.py", line 534, in figure
    **kwargs)
  File "/home/ubuntu/miniconda3/envs/urbs/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 170, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/ubuntu/miniconda3/envs/urbs/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 176, in new_figure_manager_given_figure
    canvas = cls.FigureCanvas(figure)
  File "/home/ubuntu/miniconda3/envs/urbs/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 35, in __init__
    super(FigureCanvasQTAggBase, self).__init__(figure=figure)
  File "/home/ubuntu/miniconda3/envs/urbs/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 235, in __init__
    _create_qApp()
  File "/home/ubuntu/miniconda3/envs/urbs/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 122, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable
```

**Comment by maledo** [comment]
Does this runtime error still happen with newer versions?
