### ISSUE TITLE
Solver (glpk) returned non-zero return code (3221225781)

### ISSUE THREAD

**Issue by ramielshinawy** [tum-ens/urbs#211]
when executing the runme.py script. This error appears and the following is the traceback:

Traceback (most recent call last):
  File "C:/Users/relshinawy/urbs/urbs-master (1)/urbs-master/runme.py", line 224, in <module>
    report_sites_name=report_sites_name)
  File "C:/Users/relshinawy/urbs/urbs-master (1)/urbs-master/runme.py", line 132, in run_scenario
    result = optim.solve(prob, tee=True)
  File "C:\Users\relshinawy\AppData\Local\Programs\Python\Python35\lib\site-packages\pyomo\opt\base\solvers.py", line 607, in solve
    "Solver (%s) did not exit normally" % self.name)
pyutilib.common._exceptions.ApplicationError: Solver (glpk) did not exit normally

I am not sure If I did download glpk correctly or not. I just downloaded the .Zip file and unpacked according to the instructions provided then just copied glpsol.exe to the same directory as runme.py

**Comment by sonercandas** [comment]
The solver looks to be installed properly. Can you please share the .log file generated by the solver?

**Comment by ramielshinawy** [comment]
It seems the problem has been solved. I downgraded the latest version of PYomo and glpk was not able to start as it was missing dll files so I just copied it also to the same directory.
Thanks for your support
