### ISSUE TITLE
error in plot function

### ISSUE THREAD

**Issue by kbareiss** [tum-ens/urbs#227]
During 1 node model following error occurs in the lastes urbs version.

`Solved in 0 iterations and 0.00 seconds                                            Optimal objective  0.000000000e+00
Warning: unscaled primal violation = 3.8147e-06 and residual = 3.8147e-06
Traceback (most recent call last):
  File "runme.py", line 78, in <module>
    report_sites_name=report_sites_name)
  File "/home/kbareiss/nas/mimo/urbs/runfunctions.py", line 105, in run_scenario
    figure_size=(24, 9))
  File "/home/kbareiss/nas/mimo/urbs/plot.py", line 370, in result_figures
    fig = plot(prob, com, help_sit, dt, timesteps, periodrange, **kwds)
  File "/home/kbareiss/nas/mimo/urbs/plot.py", line 258, in plot
    ax1.set_ylim((0, 0.5 + csto.loc[sit, :, com]['C Total'].sum()))
  File "/home/kbareiss/.conda/envs/urbs-env/lib/python3.7/site-packages/pandas/core
/indexing.py", line 1494, in __getitem__                                               return self._getitem_tuple(key)
  File "/home/kbareiss/.conda/envs/urbs-env/lib/python3.7/site-packages/pandas/core
/indexing.py", line 873, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/home/kbareiss/.conda/envs/urbs-env/lib/python3.7/site-packages/pandas/core/indexing.py", line 221, in _has_valid_tuple
    raise IndexingError('Too many indexers')
pandas.core.indexing.IndexingError: Too many indexers
`
comenting out following line in the plot.py function solves the problem
    #try:
    #    ax1.set_ylim((0, 0.5 + csto.loc[sit, :, com]['C Total'].sum()))
    #except KeyError:
    #    pass

**Comment by maledo** [comment]
Is it still a problem in version 1.0?
