### ISSUE TITLE
python comp.py  fails with KeyError: 'level_0'

### ISSUE THREAD

**Issue by sohumsen** [tum-ens/urbs#300]
Hi, 

The full error is 
```
Traceback (most recent call last):
  File "C:\Users\sohum\anaconda3\envs\urbs\lib\site-packages\pandas\core\indexes\base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'level_0'
```

Any help appreciated, thanks

**Comment by lodersky** [comment]
Hi,

the comp.py is outdated in the version right now. We're working on a newer version. Sorry for the inconveniences. 
For now, you can use the standard output and compare the scenarios by yourself.

**Comment by sohumsen** [comment]
ok great thanks for the help!
